apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xduqxxqzr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:34e4136336f395e5c9326fa98b520cb964b056a7@sha256:95fed7a6ebdab518a187fe1191a0ee2d45c86d826949e44f55dcedfff20c8a4f
          name: container-image
